In [11]:
import numpy as np

In [12]:
from sklearn.preprocessing import LabelBinarizer
def one_hot_encode(x):
    encoder = LabelBinarizer()
    encoder.fit(x)
    output = encoder.transform(x)
    return output

In [18]:
test_shape = np.random.choice(range(1000))
test_shape

288

In [19]:
test_numbers = np.random.choice(range(10), test_shape)
test_numbers

array([8, 1, 5, 6, 3, 7, 6, 3, 9, 8, 5, 6, 7, 0, 5, 2, 7, 8, 8, 1, 7, 2, 4,
       8, 4, 7, 4, 5, 2, 3, 9, 7, 5, 8, 4, 7, 3, 1, 1, 8, 2, 0, 2, 6, 8, 7,
       0, 0, 9, 7, 9, 5, 8, 1, 1, 4, 8, 7, 7, 8, 4, 7, 4, 7, 3, 4, 7, 9, 7,
       0, 4, 3, 2, 9, 6, 2, 5, 4, 8, 4, 2, 4, 6, 7, 4, 7, 5, 6, 8, 5, 5, 6,
       1, 8, 0, 6, 7, 7, 1, 6, 8, 5, 5, 0, 6, 8, 6, 6, 4, 4, 6, 4, 2, 6, 2,
       0, 5, 2, 6, 9, 1, 9, 3, 0, 3, 7, 5, 9, 4, 6, 4, 0, 5, 6, 1, 3, 8, 1,
       9, 4, 7, 4, 7, 3, 6, 7, 0, 8, 1, 2, 2, 8, 8, 2, 3, 8, 0, 5, 4, 4, 1,
       4, 5, 0, 1, 7, 3, 1, 7, 4, 2, 5, 3, 3, 7, 5, 5, 1, 9, 3, 5, 9, 6, 1,
       3, 8, 1, 4, 5, 3, 2, 0, 6, 8, 3, 4, 9, 9, 2, 3, 8, 0, 9, 4, 3, 7, 7,
       2, 4, 3, 6, 2, 2, 0, 6, 0, 4, 8, 7, 7, 5, 3, 5, 2, 3, 2, 4, 5, 9, 8,
       2, 7, 6, 6, 1, 7, 6, 8, 3, 5, 0, 2, 6, 6, 2, 5, 9, 0, 1, 4, 1, 5, 9,
       7, 3, 8, 0, 4, 2, 4, 7, 3, 9, 8, 4, 5, 8, 1, 7, 8, 7, 3, 3, 2, 2, 0,
       1, 7, 5, 3, 2, 1, 1, 9, 1, 8, 4, 5])

In [21]:
one_hot_out = one_hot_encode(test_numbers)
one_hot_out

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
n_encode_tests = 5
test_pairs = list(zip(test_numbers, one_hot_out))
test_pairs

[(8, array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])),
 (1, array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])),
 (5, array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])),
 (6, array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0])),
 (3, array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])),
 (7, array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])),
 (6, array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0])),
 (3, array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])),
 (9, array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])),
 (8, array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])),
 (5, array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])),
 (6, array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0])),
 (7, array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])),
 (0, array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
 (5, array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])),
 (2, array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0])),
 (7, array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])),
 (8, array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])),
 (8, array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])),
 (1, array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])),
 (7, array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])),
 (2, array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0])),
 (4, array

In [24]:
test_indices = np.random.choice(len(test_numbers), n_encode_tests)
test_indices

array([181, 241, 116, 201, 159])

In [25]:
labels = [test_pairs[test_i][0] for test_i in test_indices]
labels

[9, 2, 5, 0, 4]

In [26]:
enc_labels = np.array([test_pairs[test_i][1] for test_i in test_indices])
enc_labels

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [27]:
new_enc_labels = one_hot_encode(labels)
new_enc_labels

array([[0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [2]:
import numpy as np

In [3]:
a = [1, 2, 3]
[1, a]

[1, [1, 2, 3]]

In [14]:
import tensorflow as tf

In [15]:
a = tf.placeholder(tf.float32, [1, 2, 2, 6])

In [16]:
a

<tf.Tensor 'Placeholder_3:0' shape=(1, 2, 2, 6) dtype=float32>

In [17]:
int(a.shape[3])

6

In [18]:
b = tf.placeholder(tf.float32, [4, 5, 5, 3])

In [19]:
tf.rank(b)

<tf.Tensor 'Rank_2:0' shape=() dtype=int32>

In [20]:
c = tf.constant([[[1, 4], [3, 6]], [[2, 8], [7, 4]]])

In [21]:
d = tf.reshape(c, [-1, 2])
tf.Session().run(d)

array([[1, 4],
       [3, 6],
       [2, 8],
       [7, 4]], dtype=int32)

In [22]:
shape = b.get_shape().as_list()
shape

[4, 5, 5, 3]

In [23]:
x_tensor = tf.placeholder(tf.float32, [None, 10, 30, 6])

In [24]:
shape = x_tensor.get_shape().as_list()
shape

[None, 10, 30, 6]

In [25]:
flatten_num = tf.reduce_prod(shape[1:])
flatten_num

<tf.Tensor 'Prod_1:0' shape=() dtype=int32>

In [26]:
z = (3, 5)
r = range(4, *z)
r

range(4, 3, 5)

In [27]:
a

<tf.Tensor 'Placeholder_3:0' shape=(1, 2, 2, 6) dtype=float32>

In [32]:
a = tf.truncated_normal([2,2,2])
b = tf.Variable(a)
c = tf.Variable(a * 0.5)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    out1 = sess.run(b)
    print(out1)
    out2 = sess.run(c)
    print(out2)

[[[ 1.54002917 -1.53731382]
  [-1.24463141  0.14380817]]

 [[ 0.2709457  -0.65720129]
  [ 0.73713833  0.61710328]]]
[[[ 0.77001458 -0.76865691]
  [-0.6223157   0.07190409]]

 [[ 0.13547285 -0.32860065]
  [ 0.36856917  0.30855164]]]
